### ISSUE TITLE
wtf dude

### ISSUE THREAD

**Issue by AKNALOGIAa** [Povstalec/StargateJourney#71]
how the f u did this mod
[23:18:86] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because "p_46606_" is null
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_6933_(Level.java:198)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.ClientLevel.m_233653_(ClientLevel.java:134)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.ClientPacketListener.m_205522_(ClientPacketListener.java:635)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundSectionBlocksUpdatePacket.m_132992_(ClientboundSectionBlocksUpdatePacket.java:72)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.ClientPacketListener.m_5771_(ClientPacketListener.java:634)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundSectionBlocksUpdatePacket.m_5797_(ClientboundSectionBlocksUpdatePacket.java:64)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundSectionBlocksUpdatePacket.m_5797_(ClientboundSectionBlocksUpdatePacket.java:14)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.5/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	
	
	its very cool to see this 
	idk what u did but mb ull fix it 
	in multeplayer u cant destroy the tree and foliage 
if u need a video - ping me

**Comment by Povstalec** [comment]
> if u need a video - ping me

Yes, a video would be helpful considering the fact you said absolutely nothing regarding what you were doing. I'm guessing it has something to do with trees from what you said? But it would be much better if you actually explained what happened.

Did you click on the tree with something item? Did a kawoosh break it? In all honesty, I can't even be sure my mod has anything to do with it, considering not a single class mentioned in the error log you posted mentions it.

Usually error logs are enough to tell what happened, but in this case the function names are not even named, so 
`java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because "p_46606_" is null` tells me little to nothing regarding what actually happened.

**Comment by AKNALOGIAa** [comment]
https://cdn.discordapp.com/attachments/1115418833830817795/1203100815443624026/2024-02-03_00-09-26.mp4?ex=65cfddf2&is=65bd68f2&hm=2ef564fd77a7fce4d034a6426451e405d1aaa18e96d08040792dcd5db0d7f546&

**Comment by Povstalec** [comment]
Sorry, but I really don't think this has anything do do with Stargate Journey. Not sure how you came to the conclusion that Stargate Journey even cuased it.

Have you considered other mods causing it? Like for example the mod that causes the leaves of the trees to fall, or the mod that allows you to chop the entire tree all at once.

**Comment by AKNALOGIAa** [comment]
Of course, my friend, I had to try all my mods for updates or connections, and after several hours of checking, it turned out that only because of your mod this appears

**Comment by Povstalec** [comment]
> Of course, my friend, I had to try all my mods for updates or connections, and after several hours of checking, it turned out that only because of your mod this appears

Welp, I guess there is some weird incompatibility Stargate Journey has with another mod then, because Stargate Journey does not even come close to touching any of the code related to trees. There is nothing I can fix about this, because it's not something that's directly caused by it.

**Comment by AKNALOGIAa** [comment]
yes, I understand this perfectly well, so I have a question for you about the network connection, your mod somehow causes an error in the server’s synchronization and causes a load on the entire server, so I don’t understand how your handlers are connected to the Internet connection

**Comment by Povstalec** [comment]
The networking code is written pretty much the same as any other mods that have networking, there is nothing special or extra. You can see for yourself:
https://github.com/Povstalec/StargateJourney/blob/main/src/main/java/net/povstalec/sgjourney/common/init/PacketHandlerInit.java
